# Generated by Django 3.2.4 on 2021-06-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200, verbose_name='Country')),
                ('year', models.IntegerField(default=0, verbose_name='Year')),
                ('month', models.CharField(max_length=200, verbose_name='Month')),
                ('day', models.IntegerField(default=0, verbose_name='Day')),
                ('SolarPV_Consumption', models.IntegerField(default=0, verbose_name='SolarPV_Consumption')),
                ('Panel_Count', models.IntegerField(default=0, verbose_name='Panel_Count')),
                ('BelowUnderAVG', models.IntegerField(default=0, verbose_name='BelowUnderAVG')),
                ('Weather', models.IntegerField(default=0, verbose_name='Weather')),
            ],
        ),
    ]
